### PR TITLE
ACP-3468: Added additional payment data to payment entity

### PR DESCRIPTION
**Pull request by vol4onok**
## PR Description

https://spryker.atlassian.net/browse/ACP-3468

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Review by stereomon — COMMENTED** [review]
Why do you need to change it like this? Now every user of this needs to deal with encoding/decoding.

Why not keeping it for devs as array and only in the database as JSON?

**Review by matweew — APPROVED** [review]

**Comment by vol4onok** [comment]
@stereomon I didn't know that you already create this field as string. Now it will be string in DB and transfers

**Comment by stereomon** [comment]
This is not good as explained. Now everyone needs to deal with it, that MUST not happen.

**Comment by stereomon** [comment]
Can you please revert this?

**Comment by vol4onok** [comment]
it was partial revert of https://github.com/spryker/app-payment/pull/9

**Pull request merged**
